### ISSUE TITLE
./datalog/cookies.json sama ./datalog/data.json ga kebaca bang...

### ISSUE THREAD

**Issue by MrHecka** [MRHRTZ/Shopee-flashsale-bot#1]
![image](https://user-images.githubusercontent.com/71875420/103177939-2c070180-48b1-11eb-90f2-cb71226304de.png)

**Comment by MRHRTZ** [comment]
@MrHecka Itu sebelumnya keluar browser sama login shopee nya belum?

**Comment by MrHecka** [comment]
Sudah benar gan path chrome nya, tapi pas mau login (sebelum login) error muncul gitu

**Comment by MRHRTZ** [comment]
Programnya masih beta tar gw fix buat yg error open file cookies
