### ISSUE TITLE
urllib3 v2.0 only supports OpenSSL 1.1.1+

### ISSUE THREAD

**Issue by imkiddo** [MRHRTZ/Shopee-flashsale-bot#12]
Got this when installing

Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

🙏 pleasee

**Comment by MRHRTZ** [comment]
try to use latest python 3.11
