### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jcgaming-official** [MRHRTZ/Shopee-flashsale-bot#15]
Here is the error
`git clone https://github.com/MRHRTZ/Shopee-flashsale-bot
Cloning into 'Shopee-flashsale-bot'...
fatal: unable to access 'https://github.com/MRHRTZ/Shopee-flashsale-bot/': Could not resolve host: github.com`

**Comment by MRHRTZ** [comment]
The error does not originate from this project, but this maybe can help

- Check your connection
- Check proxy / vpn
- Reconnect WIFI

Or look for other solutions on the internet.
[Could not resolve host github.com](https://stackoverflow.com/questions/20370294/git-could-not-resolve-host-github-com-error-while-cloning-remote-repository-in)

**Comment by jcgaming-official** [comment]
> The error does not originate from this project, but this might help
> 
> - Check your connection
> - Check your Proxy / VPN
> - Reconnect WIFI
> - Try using another network
> 
> Or look for other solutions on the internet.
> [Could not resolve host github.com](https://stackoverflow.com/questions/20370294/git-could-not-resolve-host-github-com-error-while-cloning-remote-repository-in)
> 
> 

Alrighty. Thanks
