### ISSUE TITLE
Update new patch

### ISSUE THREAD

**Issue by MRHRTZ** [MRHRTZ/Shopee-flashsale-bot#16]
Because the Selenium library often does not match the webdriver used and errors often occur during checkout because Shopee continues to update their system.

We will have several updates and make tutorials for beginners

For the time being, this project can be used in several environments, but it's not certain yet.

please wait for the next update ...

**Comment by pearlxcore** [comment]
Create element configuration file at Github repo. Make the program to fetch the config from Github. No need to update whole program each time Shopee update their website.

**Comment by MRHRTZ** [comment]
Yes it's a good idea, but shopee not only changes the element configuration, but also the payload and api response that needs to remap its functions every update, and the software is very difficult to use for non programmers (*you know what I mean), so I will update with a new GUI version and stable automation lib to overcome many errors.

**Comment by pearlxcore** [comment]
Payload and response api often changed too?

I have used the API before, mainly for personal use. I stopped using the API since often received "forbidden" response, which might have been because of sending too many requests to the endpoint. At least for Malaysian Shopee.
