### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by RozeCyber** [MRHRTZ/Shopee-flashsale-bot#2]
Ini bot ny masih bisa di pake nggak ya....?
Terimakasih

**Comment by FauziFerdiansyah** [comment]
Kayanya masih cuman mungkin harus di cek kesesuaian tag html nya, ku mau  coba tp takut ke banned akun shopee nya karena yg ku liat ada beberapa ID js yg isinya check human gitu, mungkin di await nya harus dikasi waktu persekian detik, dan beberapa perubahan lain, 

Saya pernah pake bot saat komentar di IG tokopedia dan grab, wktu itu dpt HP sama voucher 1 juta, tp HP nya cuma seminggu hilang dicuri org tiba2 mungkin cara saya ga adil yah wkwk, tp voucher masih ada..

**Comment by MRHRTZ** [comment]
Secara keseluruhan kode sudah diganti, dan untuk sesi akun diharuskan login dan pasang manual, karena apabila automated akan terdeteksi anomali pada sistem.
