### ISSUE TITLE
Error (M01)

### ISSUE THREAD

**Issue by IsnaniWidhiHidayat** [MRHRTZ/Shopee-flashsale-bot#9]
I have error when checkout, this is log 
  [ Added to Cart ✔️ ]
  [ (M01): Checkout gagal karena terdapat aktivitas mencurigakan. Jika kamu tetap melanjutkan checkout, akunmu dapat diblokir. Pastikan kamu telah membaca kebijakan Shopee. ]
  [ Press Anykey To Exit This Script ]

**Comment by MRHRTZ** [comment]
This is from the shopee system that detects our webdriver emulation, can you send the url please? I tried to check using undetected chrome
